name: Build Vue
on:
  push:
    branches:
      - main
      - dev
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - name: Create .env file
      run: echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'lisarosengren'
        reponame: 'ssr-editor-vue'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
